CREATE USER peg_solitaire
IDENTIFIED BY peg
DEFAULT TABLESPACE USERS
QUOTA 1g ON USERS;

GRANT CREATE SESSION, CREATE TABLE, CREATE PROCEDURE, CREATE TYPE, CREATE SYNONYM, CREATE SEQUENCE
  TO peg_solitaire;

  
